
version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
